version: '3.7'

services:
  mysql:
    image: mysql:5.7.44
    container_name: mysql
    ports:
      - "29101:3306"
    restart: unless-stopped
    privileged: true
    ulimits:
      nproc: 655350
      nofile:
        soft: 131072
        hard: 400000
    #healthcheck:
    #  test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
    #  interval: 10s # 间隔时间
    #  timeout: 3s  # 超时时间
    #  retries: 50   # 重试次数
    command:
      [
        #设置数据库表的数据集
        '--character-set-server=utf8mb4',
        #设置数据库表的数据集
        '--collation-server=utf8mb4_unicode_ci'
      ]
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: gameframex
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    volumes:
      - ./running/mysql/mysql:/var/lib/mysql
      - ./running/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    networks:
      - gameframex_networks
  # 后台管理API
  gameframex.web.admin.api:
    image: registry.cn-shenzhen.aliyuncs.com/gameframex/gameframex.web.admin.api:1.0.0
    container_name: admin-api
    build:
      context: ./Admin.NET
      dockerfile: Dockerfile-Web-Admin
      args:
        - no-cache
    ports:
      - "20802:5005"
    environment:
      - "TZ=Asia/Shanghai"
      - "DatabaseName=gameframex"
      - "DbType=MySql"
      - "ConnectionString=Data Source=mysql;Database=gameframex;Port=3306;Uid=root;Pwd=123456;"
    links:
      - mysql
    networks:
      - gameframex_networks
  # 客户端使用API
  gameframex.web.client.api:
    image: registry.cn-shenzhen.aliyuncs.com/gameframex/gameframex.web.client.api:1.0.0
    container_name: client-api
    build:
      context: ./Admin.NET
      dockerfile: Dockerfile-Web-Api
      args:
        - no-cache
    ports:
      - "20808:80"
      # - "20809:443"
    environment:
      - "DatabaseName=gameframex"
      - "DbType=MySql"
      - "ConnectionString=Data Source=mysql;Database=gameframex;Port=3306;Uid=root;Pwd=123456;"
    links:
      - mysql
    networks:
      - gameframex_networks
    depends_on:
      - gameframex.web.admin.api
  # Web前端Vue
  gameframex.web.admin.vue:
    image: registry.cn-shenzhen.aliyuncs.com/gameframex/gameframex.web.vue:1.0.0
    container_name: admin-vue
    build:
      context: ./Web/build
      dockerfile: Dockerfile-Web-Vue
      args:
        - no-cache
    ports:
      - "20800:80"
      # - "20801:443"
    environment:
      - TZ=Asia/Shanghai
    # 这里配置映射
    # volumes:
    #   - "./running/nginx/dist:/usr/share/nginx/html"
    #   - "./running/nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf"
    #   - "./running/nginx/key:/etc/nginx/key/"
    networks:
      - gameframex_networks
    restart: always
    depends_on:
      - gameframex.web.admin.api
      - mysql
  # 文件服务器
  # gameframex.fileserver:
  #   image: registry.cn-shenzhen.aliyuncs.com/gameframex/gameframex.fileserver:1.0.0
  #   container_name: client-fileserver
  #   build:
  #     context: ./Admin.NET
  #     dockerfile: Dockerfile-FileServer
  #     args:
  #       - no-cache
  #   ports:
  #     - "20804:80"
  #     # - "20805:443"
  #   environment:
  #     - "IsOpenDirectoryBrowser=true"
  #   privileged: true
  #   volumes:
  #     - "./Bundles:/app/Bundles"
  #   networks:
  #     - gameframex_networks
networks:
  gameframex_networks:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.100.1.0/24
          gateway: 172.100.1.1
